# Generated by Django 4.1 on 2022-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meseros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(verbose_name='dni')),
                ('nombre', models.CharField(max_length=55, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=55, verbose_name='apellido')),
                ('nacionalidad', models.CharField(max_length=255, verbose_name='nacionalidad')),
                ('foto', models.ImageField(upload_to='images/', verbose_name='foto')),
            ],
        ),
    ]
