# Generated by Django 4.1 on 2022-09-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meseros',
            name='foto',
        ),
    ]
