# Generated by Django 4.1 on 2022-09-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0003_meseros_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meseros',
            name='foto',
        ),
    ]
