# Generated by Django 4.1 on 2022-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0004_remove_meseros_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='foto',
            field=models.ImageField(default='', upload_to='images/', verbose_name='foto'),
        ),
    ]
