# Generated by Django 4.1 on 2022-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(verbose_name='dni')),
                ('nombre', models.CharField(max_length=55, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=55, verbose_name='apellido')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
            ],
        ),
    ]
